name: mycolor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.2.4
  shared_preferences: 2.0.6
  http: 0.13.3
  sqflite: 2.0.0+3
  editable: 2.0.0
  flutter_gradients: 1.0.0+3
  flutter_staggered_animations: 1.0.0
  flutter_svg: 0.22.0
  rive: 0.7.26
  get_storage: 2.0.2
  liquid_progress_indicator_ns: 1.0.0
  wave: 0.2.0
  flex_color_picker: 2.1.2
  flutter_slidable: 0.6.0
  random_color: 1.0.6-nullsafety
  confetti: 0.6.0-nullsafety
  animated_theme_switcher: 2.0.1
  google_fonts: 2.1.0
  animated_text_kit: 4.2.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/rives/tree.riv
    - assets/rives/cat.riv
    - assets/rives/playpause.riv
    - assets/svgs/empty.svg
    - assets/images/1_No Connection.png
    - assets/images/4_File Not Found.png
  fonts: 
    - family: KoHo
      fonts: 
        - asset: assets/fonts/koho/KoHo-Regular.ttf
  uses-material-design: true

