name: mycolor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.2.4
  shared_preferences: 2.0.6
  http: 0.13.3
  sqflite: 2.0.0+3
  editable: 2.0.0
  flutter_gradients: 1.0.0+3
  flutter_staggered_animations: 1.0.0
  flutter_svg: 0.22.0
  rive: 0.7.26
  get_storage: 2.0.2
  liquid_progress_indicator_ns: 1.0.0
  wave: 0.2.0
  flex_color_picker: 2.1.2
  flutter_slidable: 0.6.0
  random_color: 1.0.6-nullsafety
  confetti: 0.6.0-nullsafety
  animated_theme_switcher: 2.0.1
  google_fonts: 2.1.0
  animated_text_kit: 4.2.1
  adaptive_dialog: 1.1.0
  flutter_i18n: 0.30.0
  audioplayers: 0.19.1
  just_audio: 0.9.7
  device_preview: 0.7.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  assets:
    - assets/rives/tree.riv
    - assets/rives/cat.riv
    - assets/rives/playpause.riv
    - assets/svgs/empty.svg
    - assets/images/1_No Connection.png
    - assets/images/4_File Not Found.png
    - assets/sounds/numberpicker_sound.mp3
    - assets/sounds/notify_sound.mp3
    - assets/sounds/field.mp3
    - assets/sounds/summer.mp3
    - assets/sounds/wave.mp3
  fonts:
    - family: KoHo
      fonts:
        - asset: assets/fonts/koho/KoHo-Regular.ttf
  uses-material-design: true
